<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>FrostyEditor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FrostyControls\FrostyControls.csproj" />
      <ProjectReference Include="..\FrostyCore\FrostyCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="AppIcon.ico" />
      <Resource Include="AppIcon.ico" />
      <None Remove="Images\Add.png" />
      <Resource Include="Images\Add.png" />
      <None Remove="Images\AddBookmark.png" />
      <Resource Include="Images\AddBookmark.png" />
      <None Remove="Images\AddFolder.png" />
      <Resource Include="Images\AddFolder.png" />
      <None Remove="Images\Assign.png" />
      <Resource Include="Images\Assign.png" />
      <None Remove="Images\Back.png" />
      <Resource Include="Images\Back.png" />
      <None Remove="Images\ClassRef.png" />
      <Resource Include="Images\ClassRef.png" />
      <None Remove="Images\Clear.png" />
      <Resource Include="Images\Clear.png" />
      <None Remove="Images\CloseAll.png" />
      <Resource Include="Images\CloseAll.png" />
      <None Remove="Images\CloseFolder.png" />
      <Resource Include="Images\CloseFolder.png" />
      <None Remove="Images\CloseWindow.png" />
      <Resource Include="Images\CloseWindow.png" />
      <None Remove="Images\Compile.png" />
      <Resource Include="Images\Compile.png" />
      <None Remove="Images\Database.png" />
      <Resource Include="Images\Database.png" />
      <None Remove="Images\EditLabel.png" />
      <Resource Include="Images\EditLabel.png" />
      <None Remove="Images\Exit.png" />
      <Resource Include="Images\Exit.png" />
      <None Remove="Images\Export.png" />
      <Resource Include="Images\Export.png" />
      <None Remove="Images\Filter.png" />
      <Resource Include="Images\Filter.png" />
      <None Remove="Images\Forward.png" />
      <Resource Include="Images\Forward.png" />
      <None Remove="Images\Grid.png" />
      <Resource Include="Images\Grid.png" />
      <None Remove="Images\Home.png" />
      <Resource Include="Images\Home.png" />
      <None Remove="Images\Ice.png" />
      <Resource Include="Images\Ice.png" />
      <None Remove="Images\Import.png" />
      <Resource Include="Images\Import.png" />
      <None Remove="Images\Interface.png" />
      <Resource Include="Images\Interface.png" />
      <None Remove="Images\Key.png" />
      <Resource Include="Images\Key.png" />
      <None Remove="Images\MaximizeWindow.png" />
      <Resource Include="Images\MaximizeWindow.png" />
      <None Remove="Images\Mesh.png" />
      <Resource Include="Images\Mesh.png" />
      <None Remove="Images\MinimizeWindow.png" />
      <Resource Include="Images\MinimizeWindow.png" />
      <None Remove="Images\More.png" />
      <Resource Include="Images\More.png" />
      <None Remove="Images\New.png" />
      <Resource Include="Images\New.png" />
      <None Remove="Images\Noise.png" />
      <Resource Include="Images\Noise.png" />
      <None Remove="Images\NormalMap.png" />
      <Resource Include="Images\NormalMap.png" />
      <None Remove="Images\Open.png" />
      <Resource Include="Images\Open.png" />
      <None Remove="Images\OpenAsset.png" />
      <Resource Include="Images\OpenAsset.png" />
      <None Remove="Images\OpenFolder.png" />
      <Resource Include="Images\OpenFolder.png" />
      <None Remove="Images\Pause.png" />
      <Resource Include="Images\Pause.png" />
      <None Remove="Images\Play.png" />
      <Resource Include="Images\Play.png" />
      <None Remove="Images\Properties.png" />
      <Resource Include="Images\Properties.png" />
      <None Remove="Images\Recent.png" />
      <Resource Include="Images\Recent.png" />
      <None Remove="Images\Reference.png" />
      <Resource Include="Images\Reference.png" />
      <None Remove="Images\Remove.png" />
      <Resource Include="Images\Remove.png" />
      <None Remove="Images\RemoveBookmark.png" />
      <Resource Include="Images\RemoveBookmark.png" />
      <None Remove="Images\Rename.png" />
      <Resource Include="Images\Rename.png" />
      <None Remove="Images\RenderDoc.png" />
      <Resource Include="Images\RenderDoc.png" />
      <None Remove="Images\RestoreWindow.png" />
      <Resource Include="Images\RestoreWindow.png" />
      <None Remove="Images\Revert.png" />
      <Resource Include="Images\Revert.png" />
      <None Remove="Images\Save.png" />
      <Resource Include="Images\Save.png" />
      <None Remove="Images\SaveAs.png" />
      <Resource Include="Images\SaveAs.png" />
      <None Remove="Images\Skybox.png" />
      <Resource Include="Images\Skybox.png" />
      <None Remove="Images\Stop.png" />
      <Resource Include="Images\Stop.png" />
      <None Remove="Images\ThreeD.png" />
      <Resource Include="Images\ThreeD.png" />
      <None Remove="Images\Warning.png" />
      <Resource Include="Images\Warning.png" />
      <None Remove="ChangeLog.txt" />
      <Resource Include="ChangeLog.txt" />
    </ItemGroup>

</Project>
