<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <RootNamespace>FrostyEditor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FrostyControls\FrostyControls.csproj" />
      <ProjectReference Include="..\FrostyCore\FrostyCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="AppIcon.ico" />
      <Resource Include="AppIcon.ico" />
    </ItemGroup>

</Project>
