<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWpf>true</UseWpf>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FrostySdk\FrostySdk.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Images\Clear.png" />
      <Resource Include="Images\Clear.png" />
      <None Remove="Images\CloseWindow.png" />
      <Resource Include="Images\CloseWindow.png" />
      <None Remove="Images\MaximizeWindow.png" />
      <Resource Include="Images\MaximizeWindow.png" />
      <None Remove="Images\MinimizeWindow.png" />
      <Resource Include="Images\MinimizeWindow.png" />
      <None Remove="Images\RestoreWindow.png" />
      <Resource Include="Images\RestoreWindow.png" />
    </ItemGroup>

</Project>
